package com.miteksystems.misnap.apputil

/**
 * This implementation is intended for demonstration purposes only.
 *
 * For real integrations, retrieve the license securely from a remote source.
 * Avoid including hardcoded license value in production code.
 */
object LicenseFetcher {
    fun fetch() =
        "eyJzaWduYXR1cmUiOiJ2Z1loRTExUGIxWC9NVmROVVA4cUF4RWtwU1ZEOUxEWmM0WlF1bkplUjRFYjg2aElnMEgrdGRsL3hQc3cxNllwZDFrUXNHdGJqQ3F4NnVhZmRZZTFQb3Jmck1KL0VEdzlobFRVZTg0YmdkMWtDVEg2Tmpad0swSnFMSmVJVFMxRzY1N2dvcE9LUmpDYStiazl3NE9YUVR4UDVONFh4bFg3bUdYcStEKzBJZUdsV2tLd3hoWUcvNlRVRWdQOVdMNFlzcDhDOUNZdXFyVVpFT20rTzMxVE9DZ0RreGd6QzlybEF3WFJSc09wV09XTWdHR2NmNkVTeXFZdW45UlgxcEppd1BNc0xLbE1ocE1xT1VxUlVnRjFsSVBjMlVVbFpMdERJTnBhMzFlbVh5dmlTZSsveElDSWV4TFpxanJKWjF4cGY3SDFBYkg2dzlMcW5WK0JVWnZ2bkE9PSIsInNpZ25lZCI6eyJleHBpcnkiOiIyMDMwLTEyLTMxIiwiZmVhdHVyZXMiOlsiYmFyY29kZSIsImRlcG9zaXQiLCJmYWNlIiwiZ2VuZXJpYyIsImlkIiwibmZjIiwib2RjIiwib2RlIiwidm9pY2UiLCJlbSJdLCJhcHBsaWNhdGlvbklkZW50aWZpZXIiOnsiYW5kcm9pZCI6WyJjb20ubWl0ZWtzeXN0ZW1zLm1pc25hcC5zYW1wbGVhcHAiLCJjb20ubWl0ZWtzeXN0ZW1zLm1pc25hcC5kZXZhcHAiXX0sImdwbyI6IjE2ZCIsIm9yZ2FuaXphdGlvbiI6Ik1pdGVrIFN5c3RlbXMgSW5jLiIsInZlcnNpb24iOiIxLjAifX0="
}
